### ISSUE TITLE
Crafting Station slab 1 recipe wrong.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#116]
The crafting station slab has 2 recipes, one is just the normal crafting station into a slab version, just makes another crafting station, not a slab variant. The slab crafting table into slab station works though.

**Comment by Darkosto** [comment]
Should be fixed in dev. Thanks!

**Comment by JackRuby1** [comment]
@Darkosto this is still showing the recipe of the recipe for the crafting station into a crafting station slab in 0.3.3  https://gyazo.com/9728b58800676abec1939ecc61390fca
