### ISSUE TITLE
Mulch prestige cost needs fixing.

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SkyFactory4Issues#165]
Since you reordered the mulches, you never changed the prices of them in prestige, it now goes; 1, 2, 4, 6, 12, 10, 14, 8. Unless you are leaving this as is, might want change it.

**Comment by Darkosto** [comment]
Fixed!

**Comment by battle00333** [comment]
Playing from the twitch launcher, and this issue still exists.
![Incorrect order](https://user-images.githubusercontent.com/23027074/56240996-057d4480-6095-11e9-84c7-a2fe31a112fd.gif)

**Comment by battle00333** [comment]
the same also applies to the advancements on normal mode 
![image](https://user-images.githubusercontent.com/23027074/56254094-b00a5d00-60bf-11e9-9810-c8f95171b03e.png)
