### ISSUE TITLE
Crash when hitting P in a prestige world

### ISSUE THREAD

**Issue by Studio528** [Darkosto/SkyFactory4Issues#217]
## Bug Report
 Pressing "P" crashes the game

## Expected Behaviour
 "P" should open the prestige menu, instead crashes the game.

## Steps to Reproduce (for bugs)

1. load up world and press "P"
2. game will then freeze and crash.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/gLgry0ht

## Client Information

* Modpack Version: 4.0.0
* Java Version: 1.8.0_191
* Launcher Used: old JAR launcher
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 4.0.0

* Additional Content Installed: Downgraded topography from 1.4.4 to 1.4.3 to fix crash of singleplayer, suggested by darkosto.

**Comment by Novasae** [comment]
I'm getting this crash too with MultiMC.
Logs: 
crash - https://paste.ee/p/NjpD7
latest.log - https://gist.github.com/Novasae/3bd5ea1e2f9499905e8e1b54fb3ab863

**Comment by sk2048** [comment]
If you're experiencing this issue, updating Prestige to 1.1.45 should solve it for the time being.

**Comment by Milleh84** [comment]
> If you're experiencing this issue, updating Prestige to 1.1.45 should solve it for the time being.

updating to 1.1.45 didn't work for me, still crashes when hitting P

**Comment by sk2048** [comment]
Sorry, that was my mistake, it was late when I wrote that. 1.1.46 is the version with the fix in.

**Comment by forshale** [comment]
I'd suggest using 1.1.48 since it's the latest
1.1.48:   https://minecraft.curseforge.com/projects/prestige/files/2699859

1.1.46:   https://minecraft.curseforge.com/projects/prestige/files/2699753

**Comment by Fogrits** [comment]
Well, even when using 1.1.49 (one version ahead) it still crashes

**Comment by forshale** [comment]
Did you try using 1.1.48? As ot works for me

**Comment by NinaNoodles** [comment]
my game also crashes when hitting P

[crash-2019-04-16_19.59.30-client.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3086249/crash-2019-04-16_19.59.30-client.txt)

    Modpack Version: 4.0.1
    Java Version: 1.8.0_201 (64)
    Launcher Used: JAR launcher
    Memory Allocated: 9 GB
    Server/LAN/Single Player: Single
    Optifine Installed: no
    Shaders Enabled: no

**Comment by Fogrits** [comment]
nope, 1.1.48 doesn't work
`net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1151) ~[buq.class:?]`

**Comment by PriestTheBeast** [comment]
In a multiplayer game with 4 people this bug is happening to 2, me included.
Tried to use 1.1.46 and it at least opens the window in singleplayer, but crashes when i click switch backgrounds.

**Comment by NinaNoodles** [comment]
as i am currently playing on a notebook without a gaming graphic card and the error message is about a rendering issue, maybe the problem is related to that?
This Notebook has an i7 processor, 16 GB RAM and the graphic card is Intel UHD Graphics 620

**Comment by jaredlll08** [comment]
The initial issue that this report is about has to do with non nvidia graphics cards.

That has been fixed in newer versions.

If you're still crashing, like @Fogrits is, that is a seperate issue, and I think that has to do with mismatched client and server files, doesn't matter though,
https://minecraft.curseforge.com/projects/prestige/files/2700350
that should fix that crash.

**Comment by armann24** [comment]
I'm playing in version 4.0.1 of the modpack and I'm still having the issue where I press p and it crashes. the server has Prestige-1.12.2-1.1.44.jar

is there a fix?

**Comment by sk2048** [comment]
If you aren't in control of the server, you'll just have to wait until 4.0.2 comes out.

**Comment by wanybae** [comment]
I just update Prestige-1.12.2-1.1.51 then it works!! Great!

**Comment by NinaNoodles** [comment]
I'm not sure if it is related, but now that i updated the Prestige Mod, i have a new phenomenon:
I don't need food, as I never get hungry.
This was not the case when playing without Prestige.

**Comment by jaredlll08** [comment]
> I'm not sure if it is related, but now that i updated the Prestige Mod, i have a new phenomenon:
> I don't need food, as I never get hungry.
> This was not the case when playing without Prestige.

Has nothing to do with prestige.
