### ISSUE TITLE
Server Crash when moving Lava with XNet from a Cauldron into a Seared Tank

### ISSUE THREAD

**Issue by BrainInBlack** [Darkosto/SkyFactory4Issues#308]
## Bug Report
As the title says, we had a server crash while moving lava from a cauldron to a seared tank. This happened at the exact point when i tried to insert a bit cobble, but the cauldron was full and there was a little room left in the tank.

## Possible Solution
None, at the moment.

## Steps to Reproduce (for bugs)
Will test this behavior in detail as soon as there aren't that many people on the server.

## Logs

* Server and Crash Log: https://gist.github.com/BrainInBlack/5c775e720a9741c7bf598ec959309bd6

## World Information

* Preset: Village

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.1
* Java Version: 8
* Launcher Used: MultiMC/TwitchApp
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 8
* Operating System: Linux
* Hoster/Hosting Solution: MCProHosting
* Sponge (Non-Vanilla Forge) Server: No

**Comment by BrainInBlack** [comment]
This might have been a one off, was unable to reproduce the issue on the same server with a similar setup.

**Comment by darkhax** [comment]
This issue should probably be reported to McJty so he can do a null check here anyhow.

**Comment by BrainInBlack** [comment]
Reported to McJty

**Comment by geleugim** [comment]
Looks line next release will have this resolved.
https://github.com/McJtyMods/XNet/issues/340

My server also crashes if I try to use hardened fuilducts or porcelain channels to fill the porcelain tank.

**Comment by Mozg00FF** [comment]
Similar problem, my single player world broken and not loading( cause of this problem: xnet can extract lava from cauldron. I extract lava to tank(Fluid storage tank), that already has 100mb of lava. And when tank was full game crushes

**Comment by Stonjie** [comment]
This is very close to what I have experienced. Ticking block entity crash.  Xnet controller pumping lava to lava anvil (which had vanilla armour taken from the end, not sure if the enchants were vanilla) from a barrel in a shipping container. 

I had to revert to an earlier version just to get it to load, so I lost all the items I acquired from the nether. 
[crash-2019-04-27_02.56.45-server.txt](https://github.com/Darkosto/SkyFactory4Issues/files/3123214/crash-2019-04-27_02.56.45-server.txt)


World type: Lost cities
Version: 4.0.3
Prestige: Yes
Single Player

**Comment by BrainInBlack** [comment]
If you guys pay close attention to those nice and colorful labels, then you would have known that the issue was resolved by the mod author and the SF4 team is waiting in a release. No need to add "me too" type of comments anymore.

For those unable to restart their Servers/Worlds:

1. Open the forge config (forge.cfg)
2, Enable `removeErroringTileEntities`
3. Start Server/World
4. Wait for the World to save
5. Disable `removeErroringTileEntities` again

**Comment by BrainInBlack** [comment]
Fix released with Mod Version 1.8.0 (current released version 1.8.1)

**Comment by sbrocket** [comment]
Hopefully this is a bit more helpful than a "me too". I confirmed that updating the following resolved the issue:
- McJtyLib from 1.12-3.11 to 1.12-3.50
- XNet from 1.12-1.7.6 to 1.12-1.8.1
- RFToolsPower from 1.12-1.1.2 to 1.12-1.2.0 (necessary because of new McJtyLib version)

**Comment by loldev69** [comment]
Issue is still present in version 4.1.0, if anyone is wondering.
If you don't want to manually update as per @sbrocket post, you must not use xnet fluid channels.
