### ISSUE TITLE
Compatched Storage Can't Craft Chests

### ISSUE THREAD

**Issue by onlybentley** [Darkosto/SkyFactory4Issues#436]
## Bug Report
Placing items into the builder and cannot craft the chests, and when exiting the builder it returns items to player inventory.

## Expected Behaviour
Items stay in and able to craft the chest.

## World Information

* Preset:Skylands

* Prestige: yes

* Modpack Version world created in: 

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.2
* Java Version:
* Launcher Used: multimc
* Memory Allocated: 8
* Server/LAN/Single Player: darkphans Test Server
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sLpFhaWK** [comment]
I can't make these chests either. I saw 2 videos today displaying how awesome they are, I go to my game and when I click build it rings a bell sound but no chest is crafted. I updated to 4.0.2 as well both client and server.

**Comment by Mx772** [comment]
Having same issue on 4.0.2 - Had reports that it works in singleplayer, but not multiplayer. - Tried replacing files for both compact/compatched (mod/config) no dice.

**Comment by BrainInBlack** [comment]
Confirmed fixed with mod version 1.5.1

**Comment by omriherz** [comment]
Still doesn't work for me unless I manually update the mod :(

**Comment by sk2048** [comment]
Closed does not necessarily mean the fix is released. It just means we've done all we need to do for this to be fixed in the next release.
